/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lt_myapplication_NDKTool */

#ifndef _Included_com_lt_myapplication_NDKTool
#define _Included_com_lt_myapplication_NDKTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lt_myapplication_NDKTool
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lt_myapplication_NDKTool_getStringFromNDK
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
