/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_lt_myapplication_NDKTool.h"

JNIEXPORT jstring JNICALL Java_com_lt_myapplication_NDKTool_getStringFromNDK
  (JNIEnv *env, jobject obj){
  return (*env)->NewStringUTF(env,"这里是来自jni的hello world");
  }
